### ISSUE TITLE
OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by maxclaus** [larrysu1115/cassandra-data-loader#1]
First of all, thanks for creating this project. It was really helpful.

I got this error on running the task over a CSV file with more then 2 million rows. After 600k rows the task throws this error:

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:88)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.<init>(ZipFile.java:393)
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:374)
        at java.util.jar.JarFile.getInputStream(JarFile.java:447)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
        at sun.misc.Resource.cachedInputStream(Resource.java:77)
        at sun.misc.Resource.getByteBuffer(Resource.java:160)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.cassandra.io.sstable.metadata.MetadataCollector.<init>(MetadataCollector.java:111)
        at org.apache.cassandra.io.sstable.SSTableTxnWriter.create(SSTableTxnWriter.java:109)
        at org.apache.cassandra.io.sstable.AbstractSSTableSimpleWriter.createWriter(AbstractSSTableSimpleWriter.java:63)
        at org.apache.cassandra.io.sstable.SSTableSimpleUnsortedWriter$DiskWriter.run(SSTableSimpleUnsortedWriter.java:206)
19:45:41 ERROR JVMStabilityInspector: JVM state determined to be unstable.  Exiting forcefully due to:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:88)
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.<init>(ZipFile.java:393)
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:374)
        at java.util.jar.JarFile.getInputStream(JarFile.java:447)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
        at sun.misc.Resource.cachedInputStream(Resource.java:77)
        at sun.misc.Resource.getByteBuffer(Resource.java:160)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.cassandra.io.sstable.metadata.MetadataCollector.<init>(MetadataCollector.java:111)
        at org.apache.cassandra.io.sstable.SSTableTxnWriter.create(SSTableTxnWriter.java:109)
        at org.apache.cassandra.io.sstable.AbstractSSTableSimpleWriter.createWriter(AbstractSSTableSimpleWriter.java:63)
        at org.apache.cassandra.io.sstable.SSTableSimpleUnsortedWriter$DiskWriter.run(SSTableSimpleUnsortedWriter.java:206)
19:45:41 ERROR LogTransaction: [-] was not completed, trying to abort it now
19:45:41 ERROR Ref: LEAK DETECTED: a reference (org.apache.cassandra.utils.concurrent.Ref$State@4be0d505) to class org.apache.cassandra.db.lifecycle.LogTransaction$TransactionTidier@1259099821:[-] was not released before the reference was garbage collected
```

Initially I thought it was occurring because the task was creating new "list" for every CSV row ([here](https://github.com/larrysu1115/cassandra-data-loader/blob/master/src/main/scala/org/sws9f/caxloader/CsvToSSTableWriter.scala#L62)). Then I tried to pass the columns "directly" to the addRow `writer.addRow(col1, col2, ...)`. But the same problem still ocurring. Since I couldn't find out other improvement on the code to avoid that problem I have increased the heap size and other GC configurations. Here is my current configuration:

``` shell
SBT_OPTS="-Xms512M -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:+UseGCLogFileRotation"
```

**Comment by maxclaus** [comment]
Closing this issue, since that configuration has worked for me. I have opened the issue only if someone else has the same problem in the future. Although if you know a better way of avoiding that problem, please let me know.
